---
- name: file module
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /etc/test
        state: directory
      tags:
        - create-dir

    - name: copy files from local to remote
      copy:
        src: files/test.txt
        dest: /etc/test/test.txt

    - name: test template
      template:
        src: templates/test.j2
        dest: /etc/test/test.cfg

    - name: fetch a file
      fetch:
        src: /etc/test/test.txt
        dest: ./tmp/
        flat: yes
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://www.example.com
        return_content: yes
      register: result
    - debug:
        var: result
